### ISSUE TITLE
USER STORY: Navigation bar

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#1]
EPIC: [Navigation](https://github.com/decant09/reiki/issues/5)

As a **site user** I can **easily access a navigation utility** so that **I can navigate around the site as desired**

# Acceptance Criteria
- Navigation bar is located at the top of the page
- It is accessible on all pages of the site
- Links change appearance on hover
- Dropdown menus are used to avoid overcrowding
- Links change appearance on hover
- Business logo is a link to the homepage
- Links open in current tab

### Tasks

 - [x] Create a base template that contains the navigation bar
 - [x] Insert dummy code when links to pages do not currently exist
 - [x] Create a responsive navigation bar to adapt to different screen sizes.
