### ISSUE TITLE
EPIC: Planning

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#10]
As a **developer** I can **engage in a planning phase** so that **I have a clear idea of what I am trying to achieve and adapt as necessary throughout the development process**.

# Acceptance Criteria
- Wireframes generated using mockup tool or sketches
- Entity relationship diagram showing model and data relationship
- Skeleton README with table of contents basic structure
- Project board on GitHub projects

# User Stories
- [x]  [Wireframes](https://github.com/decant09/reiki/issues/6)
- [x]  [Entity Relationship Diagram](https://github.com/decant09/reiki/issues/7)
- [x]  [Skeleton README](https://github.com/decant09/reiki/issues/8)
- [x]  [Project board](https://github.com/decant09/reiki/issues/6)

**Comment by decant09** [comment]
Added an active boolean field to the product model to allow the site admin to change status of product to active or inactive so that only active only active products will appear on the website

**Comment by decant09** [comment]
Planning phase completed in collaboration with site and business owner.
