### ISSUE TITLE
USER STORY: Registration form

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#11]
EPIC: [Registration, user accounts & profiles](https://github.com/decant09/reiki/issues/16)

As a **site user** I can **register to the website using a form** so that **registering to the website is easy and I can input all of my details as desired with required fields clearly highlighted**

# Acceptance Criteria
- Registration form displays when link to register is clicked
- Fields that are required are highlighted appropriately
- Input field at top of the form is already active and ready to receive input on page load
- Feedback to user if form is not filled out correctly
- Confirmation email sent to user to complete registration

### Tasks

 - [x] Create forms.py file
 - [x] Implement GET and POST requests as necessary
 - [x] Use csrf tags
 - [x] Style using crispy forms
 - [x] Add email functionality for registration completion step

**Comment by decant09** [comment]
Not necessary to create forms.py or implement GET or POST

**Comment by decant09** [comment]
Django allauth used for registration functionality & email confirmation system tested in the terminal
