### ISSUE TITLE
USER STORY: Login and logout

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#12]
EPIC: [Registration, user accounts & profiles](https://github.com/decant09/reiki/issues/16)

As a **site user** I can **login and logout of the website** so that **my account is secure**

# Acceptance Criteria
- Login and logout links in navigation bar which function as desired
- Manipulating the url to access a members profile redirects accordingly
- User can login using details provided at registration

### Tasks

 - [x] Add links to navigation bar
 - [x] Create error pages if profile page is accessed without authorization
 - [x] Add login required mixin or decorator

**Comment by decant09** [comment]
Added django allauth authentication

**Comment by decant09** [comment]
Added login_required decorator to profile view so that profile can only be viewed if logged in
