### ISSUE TITLE
USER STORY: Profile

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#15]
EPIC: [Registration, user accounts & profiles](https://github.com/decant09/reiki/issues/16)

As a **user** I can **have a profile automatically created upon registration** so that **I can view my order history, view my profile details and update if needed**

# Acceptance Criteria
- Profile automatically created upon registration
- Profile page for user to view their saved data
- Orders correctly display in profile page upon being placed

### Tasks

 - [x] Profile is created upon registration
 - [x] Display profile details on profile page
 - [x] Secure profile page from unauthorized access
 - [x] Display order history on profile page

**Comment by decant09** [comment]
Added a login_required to decorator to profile view so that only authorised users can view the profile
