### ISSUE TITLE
EPIC: Registration, user accounts & profiles

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#16]
As a **site user/admin** I can **register to the website and have a profile** so that **accounts can be viewed and managed**.

# Acceptance Criteria
- Have a registration form for users to sign up to the website
- Have a login and logout function for the user for account security
- Allow accounts to be closed
- Allow admin management of accounts
- Have a profile generated for users upon registration

# User Stories
- [x] [Registration form](https://github.com/decant09/reiki/issues/11)
- [x] [Login and logout](https://github.com/decant09/reiki/issues/12)
- [x] [Close account](https://github.com/decant09/reiki/issues/13)
- [x] [Admin access to manage accounts](https://github.com/decant09/reiki/issues/14)
- [x] [Profile](https://github.com/decant09/reiki/issues/15)
