### ISSUE TITLE
USER STORY: View products in cart

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#18]
EPIC: [Cart and checkout](https://github.com/decant09/reiki/issues/23)

As a **site user** I can **view the products that are in my cart** so that **I can keep a track on what is in the cart before checking out**

# Acceptance Criteria
- Cart modal displayed each time an item is added showing what is in the cart
- Modal can be closed
- Cart icon in navigation bar can be clicked to take user to the cart page displaying the items in the cart

### Tasks

 - [x] Use bootstrap toasts to display cart modal
 - [x] Allow user to close modal
 - [x] Create page to display all items in the cart before checking out
