### ISSUE TITLE
USER STORY: Login dependent navigation  bar

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#2]
EPIC: [Navigation](https://github.com/decant09/reiki/issues/5)

As a **site user** I can **see a navigation bar that is dependent on login status** so that **I can see if I am logged in or not and access areas of the site that are only available to logged in users**

# Acceptance Criteria
- Navigation bar displays a signup/register link if the user is not logged in
- Navigation bar displays a login link if the user is not logged in
- Navigation bar displays a logout link if the user in signed in

### Tasks

 - [x] Add a check to determine if the site user is logged in or not
 - [x] Add code to display relevant links
 - [x] Add relevant links to allow user to register, login or logout
