### ISSUE TITLE
USER STORY: Checkout and stripe payments

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#20]
EPIC: [Cart and checkout](https://github.com/decant09/reiki/issues/23)

As a **site  user** I can **checkout and purchase the items in my cart using a trustworthy software** so that **I can purchase the items in my cart in a secure fashion**

# Acceptance Criteria
- Checkout button taking the user to a checkout page
- Checkout page contains a form to input details
- Details prepopulated if user is signed in
- Page displayed with confirmation of purchase and purchase details

### Tasks

 - [x] Clearly labelled checkout button in toast modal and on cart page
 - [x] Implement stripe payment utility
 - [x] Test webhooks
 - [x] Add confirmation page and invoice template

**Comment by decant09** [comment]
Confirmation page completed with order details and a confirmation email sent with order synopsis but in order to view the invoice the user can create an account where the order history is saved.
