### ISSUE TITLE
USER STORY: Running total of cart displayed

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#22]
EPIC: [Cart and checkout](https://github.com/decant09/reiki/issues/23)

As a **site user** I can **view the running total of the items in my cart** so that **I can keep track on my spend and delivery costs if applicable**

# Acceptance Criteria
- Cart modal displays running total
- Cart and checkout page displays running total
- Deficit for free delivery displayed to allow user to increase spend to receive free delivery

### Tasks

 - [x] Apply formula to keep track of total cost of items in the cart
 - [x] Apply formula to calculate delivery cost
 - [x] Display these values as intended
