### ISSUE TITLE
EPIC: Cart and checkout

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#23]
As a **site user** I can **manage the items in my cart and complete my purchase** so that **I can successfully purchase the items I desire**.

# Acceptance Criteria
- Products can be added to the cart
- Cart contents are accessible
- Contents of cart can be modified
- Items in cart can be purchased using stripe payments
- Email confirmation of purchase sent to customer upon purchase success
- Running total of items in cart available to site user throughout and at the end of the shopping experience

# User Stories
- [x]  [Add products to cart](https://github.com/decant09/reiki/issues/17)
- [x]  [View products in cart](https://github.com/decant09/reiki/issues/18)
- [x]  [Add or remove products](https://github.com/decant09/reiki/issues/19)
- [x]  [Checkout and stripe payments](https://github.com/decant09/reiki/issues/20)
- [x]  [Confirmation email](https://github.com/decant09/reiki/issues/21)
- [x]  [Running total of cart displayed](https://github.com/decant09/reiki/issues/22)
