### ISSUE TITLE
USER STORY: Add products

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#24]
EPIC: [Admin and store management](https://github.com/decant09/reiki/issues/29)

As an **admin** I can **add products to the database** so that **the products are available for the site user to view and purchase**

# Acceptance Criteria
- Products can be added form the live site or from the admin site
- Product image can be uploaded
- Product details can be entered
- Price can be added

### Tasks

 - [x] Setup database to store product data
 - [x] Create product and category models for product data particulars
 - [x] Create admin side ability to add product to database
 - [x] Create product list pages
 - [x] Add ability to add products on live site

**Comment by decant09** [comment]
Added an active boolean field to the product model in the entity relationship diagram to allow the site admin to change status of product to active or inactive so that only active only active products will appear on the website.
