### ISSUE TITLE
USER STORY: Edit products

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#25]
EPIC: [Admin and store management](https://github.com/decant09/reiki/issues/29)

As an **admin** I can **edit products in the database** so that **I can make adjustments to any details that may be incorrect or update details to reflect more up to date values**

# Acceptance Criteria
- Edit product functionality on admin site and on live site
- All product details can be edited
- Once updated new values can be saved and appear on the live site

### Tasks

 - [x] Add view to handle edit capability
 - [x] Add edit product functionality on admin site
 - [x] Add button to allow edit action on live site
