### ISSUE TITLE
USER STORY: Delete products

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#26]
EPIC: [Admin and store management](https://github.com/decant09/reiki/issues/29)

As an **admin** I can **delete products from the database** so that **products which are not intended to appear on the live site can be removed**

# Acceptance Criteria
- Admin site has delete product functionality
- Live site has a button to delete products for users with admin status
- Deleting product successfully removes it from the database

### Tasks

 - [x] Ensure admin site has delete product functionality
 - [x] Add view to handle delete functionality 
 - [x] Add button to enact delete action
