### ISSUE TITLE
USER STORY: View orders

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#27]
EPIC: [Admin and store management](https://github.com/decant09/reiki/issues/29)

As a **site user/admin** I can **view all orders placed on the site** so that **so that I have a record of orders and in case any order needs to be reviewed**

# Acceptance Criteria
- Admin site should have a recorded list of orders with relevant details attached
- User profile page should have a record of orders placed by that user

### Tasks

 - [x] Create order model
 - [x] Add history of orders to admin site
 - [x] Add history or orders to users profile page
