### ISSUE TITLE
USER STORY: Manage profiles

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#28]
EPIC: [Admin and store management](https://github.com/decant09/reiki/issues/29)

As a **site user/admin** I can **view and manage my profile, or other profiles as an admin** so that **profile details are up to date and correct or so that profiles can be deleted**

# Acceptance Criteria
- The admin site should have an area to view all profiles
- The live site should have an area where the logged in user can view their profile
- Both areas should have update and delete functionality

### Tasks

 - [x] Create a user profile model
 - [x] Create an area on the admin site to view with user profiles with the intended fields displayed
 - [x] Create an area on the live for the user to view their profile
 - [x] Add create, update, and delete functionality on the admin site
 - [x] Add update and delete functionality on the live site for signed in user

**Comment by decant09** [comment]
Create, update, delete functionality built into django

**Comment by decant09** [comment]
The implementation of a user being able to delete their own profile on the site was not completed. In order to delete a profile the user can contact the website admin.
