### ISSUE TITLE
EPIC: Admin and store management

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#29]
As an **admin/site owner** I can **manage the products available on the store and manage orders and profiles** so that **I can add new products, remove old products, or update current products so that the most up to date and correct information is displayed to the site user at all times and also view orders and profiles in case of customer queries**.

# Acceptance Criteria
- Add products from the admin side and on the live site
- Edit the product details from the admin side and on the live site
- Delete products from the admin side and on the live site
- View a history of orders from the admin site
- View profiles from the admin site with an ability to create, update, or delete profiles as required

# User Stories
- [x] [Add products](https://github.com/decant09/reiki/issues/24)
- [x] [Edit products](https://github.com/decant09/reiki/issues/25)
- [x] [Delete products](https://github.com/decant09/reiki/issues/26)
- [x] [View orders](https://github.com/decant09/reiki/issues/27)
- [x] [Manage profiles](https://github.com/decant09/reiki/issues/28)
