### ISSUE TITLE
USER STORY: Categorize products

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#30]
EPIC: [Product views and sorting](https://github.com/decant09/reiki/issues/33)

As a **site user** I can **view products as a list within a category** so that **I can filter the products that I wish to view**

# Acceptance Criteria
- There is an area in the navigation bar to select a category
- Selecting a category displays only the products within that category
- The page displays a title or obvious text making it clear to the user what category they are viewing

### Tasks

 - [x] Create a categories model
 - [x] Link products model to categories model with foreign key
 - [x] Create page to display products 
 - [x] Create filters to display products of a certain category
