### ISSUE TITLE
USER STORY: View products as a list

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#31]
EPIC: [Product views and sorting](https://github.com/decant09/reiki/issues/33)

As a **site user** I can **view products in a listed style that improves user experience** so that **I can browse the range of products with some key details available and in a manner which is pleasant to experience**

# Acceptance Criteria
- Products can be viewed on a products list page
- Products are displayed in rows and columns
- Three items per row displayed on large screen sizes reducing to two and one per row as screen size reduces
- Products details such as image, name, and price are displayed on the product list page 

### Tasks

 - [x] Create a page to display products
 - [x] Set up a bootstrap card to display product with desired details
 - [x] Set up responsive behaviour for number of products per row
