### ISSUE TITLE
USER STORY: View product details

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#32]
EPIC: [Product views and sorting](https://github.com/decant09/reiki/issues/33)

As a **site user** I can **click on a product on the product list page** so that **I am taken to a page that displays the product along with some extra details and I can learn more about the product**

# Acceptance Criteria
- Product can be clicked on taking the user to the product detail page
- The product detail displays extra information such as a description which is not available on the product list page
- A back button exists to allow the user to return to the previous product list page
- There should be an add to cart button on this page

### Tasks

 - [x] Add a link to the product list page to link to that products product detail page
 - [x] Create a bootstrap card that contains all of the intended information to be displayed on the product detail page
 - [x] Add a back button link to the product list page
 - [x] Add an add to cart button
