### ISSUE TITLE
EPIC: Product views and sorting

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#33]
As a **site user** I can **view products in a list and filter by category** so that **I can view all the products on offer on the site in a user friendly fashion**.

# Acceptance Criteria
- Products can be viewed by category
- Products can be viewed as a list
- Each product has its own product detail page

# User Stories
- [x] [Categorize products](https://github.com/decant09/reiki/issues/30)
- [x] [View products as a list](https://github.com/decant09/reiki/issues/31)
- [x] [View product details](https://github.com/decant09/reiki/issues/32)
