### ISSUE TITLE
USER STORY: View list of FAQs

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#34]
EPIC: [FAQ and contact](https://github.com/decant09/reiki/issues/37)

As a **site user** I can **view a list of other users frequently asked questions** so that **if I have an issue with the site or service I can see if there is a question there that is similar to mine**

# Acceptance Criteria
- There must be an easily found link to the FAQ page
- The FAQ page must clearly list out the most frequently asked questions

### Tasks

 - [x] Create a model to store the FAQ data
 - [x] Create a list of FAQs
 - [x] Display the FAQs on a distinct page
