### ISSUE TITLE
USER STORY: Contact form

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#36]
EPIC: [FAQ and contact](https://github.com/decant09/reiki/issues/37)

As a **site user** I can **access a contact form if I cannot resolve the issue at hand by referring to the FAQs** so that **I have a means to contact the business to request extra information or to make contact for queries on products or services**

# Acceptance Criteria
- There should be a link to a contact form that is easy to locate
- There should be a specific page or area for that form
- The form should be clearly labelled to inform the user as to what information is needed
- There should be a button to submit the form
- A message should appear to let the user know the query has been successfully submitted and that someone will be in touch shortly
- The page should reload with a clear form displayed after successful submission

### Tasks

 - [x] Create a form with all of the desired fields
 - [x] Create a contact page and links to that page
 - [x] Add a button to submit the form
 - [x] Add a toast message to confirm successful submission
