### ISSUE TITLE
EPIC: FAQ and contact

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#37]
As a **site user** I can **access FAQs and a contact form on the site** so that **I can resolve any issues or queries that I may have**.

# Acceptance Criteria
- The user should be able to easily locate a FAQs page
- The FAQ page should display a list of questions accompanied by their respective answers
- The user should be able to easily locate a contact us page

# User Stories
- [x] [View list of FAQs](https://github.com/decant09/reiki/issues/34)
- [x] [View list of FAQ answers](https://github.com/decant09/reiki/issues/35)
- [x] [Contact form](https://github.com/decant09/reiki/issues/36)
