### ISSUE TITLE
USER STORY: Subscribe to newsletter

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#38]
EPIC: [Newsletter and blog](https://github.com/decant09/reiki/issues/41)

As a **site user** I can **subscribe to a newsletter from the business** so that **I am kept up to date with any new offers or services that become available on the site**

# Acceptance Criteria
- A subscribe to newsletter button should be found at the bottom of the homepage
- Clicking the button should take the user to a form to input their email address
- The user should receive a conformation email stating that they are signed up to receive the newsletter

### Tasks

 - [x] Setup a mailchimp newsletter account to facilitate the service
 - [x] Create a button to allow the user to subscribe to the newsletter
 - [x] Setup email notifications if that is not an included aspect of the mailchimp service
