### ISSUE TITLE
USER STORY: Unsubscribe from newsletter

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#39]
EPIC: [Newsletter and blog](https://github.com/decant09/reiki/issues/41)

As a **site user** I can **unsubscribe from the newsletter if I have previously signed up** so that **I can remove my email from the mailing list if I no longer want to receive the newsletter**

# Acceptance Criteria
- There should be a portal to allow the user to unsubscribe from the newsletter
- The newsletter email should contain a link to unsubscribe
- The link should take the user to the website prompting them to login if not already
- The webpage displayed should have a button clearly labelled unsubscribe
- Clicking the button should successfully remove the users email address from the database
- A success message should appear to notify the user that they have successfully unsubscribed

### Tasks

 - [x] Ensure there is an unsubscribe link in the mailchimp newsletter email
 - [x] Create the unsubscribe page
 - [x] Add an unsubscribe button to the page
 - [x] Add the logic to remove users email from the database
 - [x] Create the success message that notifies the user

**Comment by decant09** [comment]
Unsubscribe function in mailchimp or can contact admin to remove from subscribed list
