### ISSUE TITLE
USER STORY: Error pages

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#4]
EPIC: [Navigation](https://github.com/decant09/reiki/issues/5)

As a **site user** I can **have a page displayed to me with an error code related message and a navigation button to take me to a different area of the site** so that **I can receive information relating to the error and navigate away from the page and continue my browsing experience**

# Acceptance Criteria
- Relevant error pages display when an error is triggered
- Error code related message is displayed to user to inform them as to the issue
- Error page contains a button to allow the user to navigate away form the page to a different area of the site in a graceful manner

### Tasks

 - [x] Create 403, 404 and 500 html files
 - [x] Apply site wide styling to the pages
 - [x] Display error code message on each page
 - [x] Add buttons to the pages

**Comment by decant09** [comment]
Add error handler in views & url for templates
