### ISSUE TITLE
USER STORY: Blog

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#40]
EPIC: [Newsletter and blog](https://github.com/decant09/reiki/issues/41)

As a **site user** I can **view a blog page with posts from the business** so that **I can keep up to date with any thoughts or research that the business wishes to share**

# Acceptance Criteria
- There should be a link to the blog page in the navigation bar
- The link should take the user to the blog page
- Blog postings should be in chronological order with the most recent appearing at the top
- Each posting should display details such as a title, date, image and a short blog excerpt
- Each posting should be clickable and take the user to the expanded version of the blog post 

### Tasks

 - [ ] Add a model for the data required for the blog
 - [ ] Create link to blog page in navigation bar
 - [ ] Create blog list page
 - [ ] Create bootstrap cards to display blog entries
 - [ ] Add link to card to take user to the blog post detail page
 - [ ] Create blog post detail page
