### ISSUE TITLE
EPIC: Newsletter and blog

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#41]
As a **site user/site owner** I can **sign up to a newsletter and read a blog/distribute a newsletter and post blog entries** so that **I can be notified of any new products, services or research findings/I can market new products or services to my subscribed members or share my thoughts on new findings in the area of the business**.

# Acceptance Criteria
- There should be a newsletter that the user can both subscribe and unsubscribe to and from
- There be a home for blog posts on the website

# User Stories
- [x] [Subscribe to newsletter](https://github.com/decant09/reiki/issues/38)
- [x] [Unsubscribe from newsletter](https://github.com/decant09/reiki/issues/39)
- [x] [Blog](https://github.com/decant09/reiki/issues/40)

**Comment by decant09** [comment]
Blog not included in this version of website. Future implementation.
