### ISSUE TITLE
EPIC: Search engine optimization

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#49]
As a **developer/site owner** I can **take steps to improve the visibility of the website on search engines** so that **more traffic flows to the website**.

# Acceptance Criteria
- There should be a robots file
- There should sitemap file
- Meta tags should be included in the head element

# User Stories
- [x] [Robots file](https://github.com/decant09/reiki/issues/46)
- [x] [Sitemap file](https://github.com/decant09/reiki/issues/47)
- [x] [Meta tags](https://github.com/decant09/reiki/issues/48)
