### ISSUE TITLE
EPIC: Navigation

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#5]
As a **site** I can **easily navigate around the website in a graceful manner** so that **my experience of using the site is a pleasure**.

# Acceptance Criteria
- The navigation bar remains in a constant location across all areas of the website
- Register, login, and logout links appear correctly
- Buttons appear on pages to allow users to navigate away from that page if desired
- If the user encounters an error the relevant error page is displayed along with navigation buttons to navigate away form that page

# User Stories
- [x]  [Navigation bar](https://github.com/decant09/reiki/issues/1)
- [x]  [Login dependent navigation bar](https://github.com/decant09/reiki/issues/2)
- [x]  [Navigation buttons](https://github.com/decant09/reiki/issues/3)
- [x]  [Error pages](https://github.com/decant09/reiki/issues/4)
