### ISSUE TITLE
USER STORY: Skeleton README

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#8]
EPIC: [Planning](https://github.com/decant09/reiki/issues/10)

As a **developer** I can **create a skeleton README in the early stages of the project** so that **I can use the README as a tool for documentation as I progress through development process**

# Acceptance Criteria
- Table of contents
- Sections and headings
- Document information that is currently available

### Tasks

 - [x] Use previous project README and clear out data so that bare skeleton is left
 - [x] Leave relevant documentation in place
 - [x] Insert available documentation
