### ISSUE TITLE
USER STORY: Project board

### ISSUE THREAD

**Issue by decant09** [decant09/reiki#9]
EPIC: [Planning](https://github.com/decant09/reiki/issues/10)

As a **developer** I can **create a project board using GitHub projects** so that **I can use agile methodologies and effectively manage the project timeline and adapt the project as needed**

# Acceptance Criteria
- GitHub project board
- Epics
- User stories
- Labels
- Milestones

### Tasks

 - [x] Create a project on GitHub pages and link it to repository
 - [x] Create epics and user stories linked to the epic
 - [x] Add labels and milestones to each epic and user story

**Comment by decant09** [comment]
Epics and user stories created with custom labels and milestones attached

**Comment by decant09** [comment]
Project board created and epics and user stories added to todo column
